# Generated by Django 4.2.30 on 2026-04-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horizon_days', models.PositiveIntegerField(default=30)),
                ('booking_growth_pct', models.FloatField(default=0.0)),
                ('cancellation_rate', models.FloatField(default=0.0)),
                ('projected_bookings', models.PositiveIntegerField(default=0)),
                ('projected_commission', models.FloatField(default=0.0)),
                ('baseline_commission', models.FloatField(default=0.0)),
                ('uplift_commission', models.FloatField(default=0.0)),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=50)),
                ('segment', models.CharField(max_length=120)),
                ('projected_commission', models.FloatField(default=0.0)),
                ('projected_bookings', models.PositiveIntegerField(default=0)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='forecasting.forecastrun')),
            ],
            options={
                'ordering': ['dimension', '-projected_commission', 'segment'],
            },
        ),
    ]
